name: Pull and Scream

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: "self-hosted"

        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Status
              run: "cd c:/source/Consulting/intranet & git status"