name: Pull and Scream

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: "self-hosted"

        steps:
            - name: "Cd intranet and pull"
              run: "cd c:/source/Consulting/intranet ;; git pull"
            - name: Status
              run: "git status"
